const ERROR_CODE = Object.freeze({
  NOT_UNIQUE: 'NOT_UNIQUE',
  INVALID_STRING_SIZE: 'INVALID_STRING_SIZE',
  WRONG_ERROR_CODE: 'WRONG_ERROR_CODE',
  WRONG_FORMAT: 'WRONG_FORMAT',
});

export default ERROR_CODE;
